#!/bin/bash

while [[ $# > 0 ]]
do
	case "$1" in
    	-n)
      		varg1=${2}
      		shift
      		;;
    	*)
      		vargx[i]="$1"
      		((i=i+1))
      		;;
  	esac
  	shift
done

NAMESPACE=$varg1
AGEINSEC=${vargx[0]}

TTY=$(tty)
AGEINSEC=${AGEINSEC:-'0s'}

if [ ${TTY} ]
then
	if [ ${NAMESPACE} ]
	then
		for POD in $(kubectl get pods -n ${NAMESPACE} -oname)
		do
			kubectl logs -n ${NAMESPACE} ${POD} --prefix --since=${AGEINSEC} --all-containers -f > ${TTY} &
		done
	else
		echo "Error. Required namespace not specified."
		echo "Usage: kubectl nslogs -n namespace [ SINCE - only return logs newer than a relative duration like 5s, 2m, or 3h. Defaults to all logs ]"
		exit 1
	fi
else
	echo "Error..."
	exit 1
fi

KillJobs() {
    for job in $(jobs -p); do
            kill -s SIGTERM $job > /dev/null 2>&1
    done
}

TrapQuit() {
    KillJobs
    exit 0
}

trap TrapQuit EXIT SIGINT SIGTERM

while true
do
	sleep 86400
done
